/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/layouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Layouts */
        get: operations["core_routes_layouts_list_layouts"];
        put?: never;
        /** Create Layout */
        post: operations["core_routes_layouts_create_layout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layouts/{layout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layout */
        get: operations["core_routes_layouts_get_layout"];
        put?: never;
        post?: never;
        /** Delete Layout */
        delete: operations["core_routes_layouts_delete_layout"];
        options?: never;
        head?: never;
        /** Update Layout */
        patch: operations["core_routes_layouts_update_layout"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** LayoutRead */
        LayoutRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Content */
            content?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LayoutCreate */
        LayoutCreate: {
            /** Name */
            name: string;
            /** Content */
            content?: string | null;
        };
        /** LayoutUpdate */
        LayoutUpdate: {
            /** Name */
            name?: string | null;
            /** Content */
            content?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    core_routes_layouts_list_layouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutRead"][];
                };
            };
        };
    };
    core_routes_layouts_create_layout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutRead"];
                };
            };
        };
    };
    core_routes_layouts_get_layout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutRead"];
                };
            };
        };
    };
    core_routes_layouts_delete_layout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    core_routes_layouts_update_layout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layout_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutRead"];
                };
            };
        };
    };
}
